In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv('../dataset/HR-Employee-Attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [3]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [4]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [5]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [6]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [7]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 448
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [12]:
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("checkpoints/",exist_ok=True)
checkpoint_path = "checkpoints/weights.{epoch:02d}.hdf5"

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Create a callback that saves the model's weights every 5 epochs
cp_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq=1000)

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
35/35 [==============================] - 0s 549us/step - loss: 0.5673 - accuracy: 0.7314
Epoch 2/100
35/35 [==============================] - 0s 553us/step - loss: 0.5036 - accuracy: 0.7840
Epoch 3/100
35/35 [==============================] - 0s 537us/step - loss: 0.4700 - accuracy: 0.8158
Epoch 4/100
35/35 [==============================] - 0s 543us/step - loss: 0.4474 - accuracy: 0.8321
Epoch 5/100
35/35 [==============================] - 0s 544us/step - loss: 0.4314 - accuracy: 0.8330
Epoch 6/100
35/35 [==============================] - 0s 564us/step - loss: 0.4186 - accuracy: 0.8348
Epoch 7/100
35/35 [==============================] - 0s 563us/step - loss: 0.4079 - accuracy: 0.8412
Epoch 8/100
35/35 [==============================] - 0s 542us/step - loss: 0.3976 - accuracy: 0.8430
Epoch 9/100
35/35 [==============================] - 0s 643us/step - loss: 0.3881 - accuracy: 0.8439
Epoch 10/100
35/35 [==============================] - 0s 542us/step - loss: 0.3794 - accuracy: 0.8412
Epoch 11/100
35/35 [==============================] - 0s 553us/step - loss: 0.3706 - accuracy: 0.8457
Epoch 12/100
35/35 [==============================] - 0s 593us/step - loss: 0.3634 - accuracy: 0.8521
Epoch 13/100
35/35 [==============================] - 0s 625us/step - loss: 0.3567 - accuracy: 0.8539
Epoch 14/100
35/35 [==============================] - 0s 569us/step - loss: 0.3505 - accuracy: 0.8639
Epoch 15/100
35/35 [==============================] - 0s 530us/step - loss: 0.3444 - accuracy: 0.8630
Epoch 16/100
35/35 [==============================] - 0s 542us/step - loss: 0.3389 - accuracy: 0.8648
Epoch 17/100
35/35 [==============================] - 0s 577us/step - loss: 0.3336 - accuracy: 0.8693
Epoch 18/100
35/35 [==============================] - 0s 543us/step - loss: 0.3286 - accuracy: 0.8639
Epoch 19/100
35/35 [==============================] - 0s 541us/step - loss: 0.3245 - accuracy: 0.8702
Epoch 20/100
35/35 [==============================] - 0s 593us/step - loss: 0.3198 - accuracy: 0.8702
Epoch 21/100
35/35 [==============================] - 0s 594us/step - loss: 0.3160 - accuracy: 0.8721
Epoch 22/100
35/35 [==============================] - 0s 538us/step - loss: 0.3111 - accuracy: 0.8730
Epoch 23/100
35/35 [==============================] - 0s 557us/step - loss: 0.3069 - accuracy: 0.8739
Epoch 24/100
35/35 [==============================] - 0s 566us/step - loss: 0.3040 - accuracy: 0.8711
Epoch 25/100
35/35 [==============================] - 0s 549us/step - loss: 0.2997 - accuracy: 0.8793
Epoch 26/100
35/35 [==============================] - 0s 549us/step - loss: 0.2961 - accuracy: 0.8793
Epoch 27/100
35/35 [==============================] - 0s 563us/step - loss: 0.2931 - accuracy: 0.8811
Epoch 28/100
35/35 [==============================] - 0s 544us/step - loss: 0.2895 - accuracy: 0.8857
Epoch 29/100
 1/35 [..............................] - ETA: 0s - loss: 0.2271 - accuracy: 0.9062
Epoch 00029: saving model to checkpoints/weights.29.hdf5
35/35 [==============================] - 0s 6ms/step - loss: 0.2868 - accuracy: 0.8829
Epoch 30/100
35/35 [==============================] - 0s 570us/step - loss: 0.2832 - accuracy: 0.8857
Epoch 31/100
35/35 [==============================] - 0s 607us/step - loss: 0.2807 - accuracy: 0.8875
Epoch 32/100
35/35 [==============================] - 0s 556us/step - loss: 0.2773 - accuracy: 0.8902
Epoch 33/100
35/35 [==============================] - 0s 516us/step - loss: 0.2748 - accuracy: 0.8911
Epoch 34/100
35/35 [==============================] - 0s 566us/step - loss: 0.2724 - accuracy: 0.8938
Epoch 35/100
35/35 [==============================] - 0s 546us/step - loss: 0.2696 - accuracy: 0.8929
Epoch 36/100
35/35 [==============================] - 0s 549us/step - loss: 0.2671 - accuracy: 0.8920
Epoch 37/100
35/35 [==============================] - 0s 553us/step - loss: 0.2641 - accuracy: 0.8956
Epoch 38/100
35/35 [==============================] - 0s 564us/step - loss: 0.2619 - accuracy: 0.8947
Epoch 39/100
35/35 [==============================] - 0s 590us/step - loss: 0.2592 - accuracy: 0.8947
Epoch 40/100
35/35 [==============================] - 0s 534us/step - loss: 0.2574 - accuracy: 0.8966
Epoch 41/100
35/35 [==============================] - 0s 554us/step - loss: 0.2552 - accuracy: 0.9002
Epoch 42/100
35/35 [==============================] - 0s 563us/step - loss: 0.2526 - accuracy: 0.8975
Epoch 43/100
35/35 [==============================] - 0s 531us/step - loss: 0.2507 - accuracy: 0.8993
Epoch 44/100
35/35 [==============================] - 0s 561us/step - loss: 0.2486 - accuracy: 0.8975
Epoch 45/100
35/35 [==============================] - 0s 549us/step - loss: 0.2465 - accuracy: 0.8966
Epoch 46/100
35/35 [==============================] - 0s 592us/step - loss: 0.2449 - accuracy: 0.8975
Epoch 47/100
35/35 [==============================] - 0s 552us/step - loss: 0.2426 - accuracy: 0.9011
Epoch 48/100
35/35 [==============================] - 0s 551us/step - loss: 0.2408 - accuracy: 0.9038
Epoch 49/100
35/35 [==============================] - 0s 557us/step - loss: 0.2393 - accuracy: 0.9020
Epoch 50/100
35/35 [==============================] - 0s 547us/step - loss: 0.2377 - accuracy: 0.9029
Epoch 51/100
35/35 [==============================] - 0s 613us/step - loss: 0.2364 - accuracy: 0.9038
Epoch 52/100
35/35 [==============================] - 0s 603us/step - loss: 0.2347 - accuracy: 0.9029
Epoch 53/100
35/35 [==============================] - 0s 731us/step - loss: 0.2328 - accuracy: 0.9056
Epoch 54/100
35/35 [==============================] - 0s 599us/step - loss: 0.2316 - accuracy: 0.9038
Epoch 55/100
35/35 [==============================] - 0s 640us/step - loss: 0.2297 - accuracy: 0.9074
Epoch 56/100
35/35 [==============================] - 0s 562us/step - loss: 0.2283 - accuracy: 0.9074
Epoch 57/100
35/35 [==============================] - 0s 648us/step - loss: 0.2266 - accuracy: 0.9083
Epoch 58/100
 1/35 [..............................] - ETA: 0s - loss: 0.3261 - accuracy: 0.8750
Epoch 00058: saving model to checkpoints/weights.58.hdf5
35/35 [==============================] - 0s 863us/step - loss: 0.2255 - accuracy: 0.9102
Epoch 59/100
35/35 [==============================] - 0s 599us/step - loss: 0.2243 - accuracy: 0.9074
Epoch 60/100
35/35 [==============================] - 0s 571us/step - loss: 0.2232 - accuracy: 0.9074
Epoch 61/100
35/35 [==============================] - 0s 553us/step - loss: 0.2211 - accuracy: 0.9102
Epoch 62/100
35/35 [==============================] - 0s 630us/step - loss: 0.2196 - accuracy: 0.9111
Epoch 63/100
35/35 [==============================] - 0s 629us/step - loss: 0.2191 - accuracy: 0.9093
Epoch 64/100
35/35 [==============================] - 0s 601us/step - loss: 0.2174 - accuracy: 0.9111
Epoch 65/100
35/35 [==============================] - 0s 606us/step - loss: 0.2169 - accuracy: 0.9129
Epoch 66/100
35/35 [==============================] - 0s 570us/step - loss: 0.2149 - accuracy: 0.9120
Epoch 67/100
35/35 [==============================] - 0s 625us/step - loss: 0.2135 - accuracy: 0.9120
Epoch 68/100
35/35 [==============================] - 0s 631us/step - loss: 0.2125 - accuracy: 0.9111
Epoch 69/100
35/35 [==============================] - 0s 523us/step - loss: 0.2113 - accuracy: 0.9129
Epoch 70/100
35/35 [==============================] - 0s 595us/step - loss: 0.2104 - accuracy: 0.9156
Epoch 71/100
35/35 [==============================] - 0s 546us/step - loss: 0.2092 - accuracy: 0.9120
Epoch 72/100
35/35 [==============================] - 0s 673us/step - loss: 0.2075 - accuracy: 0.9156
Epoch 73/100
35/35 [==============================] - 0s 709us/step - loss: 0.2062 - accuracy: 0.9156
Epoch 74/100
35/35 [==============================] - 0s 628us/step - loss: 0.2058 - accuracy: 0.9165
Epoch 75/100
35/35 [==============================] - 0s 874us/step - loss: 0.2040 - accuracy: 0.9174
Epoch 76/100
35/35 [==============================] - 0s 860us/step - loss: 0.2028 - accuracy: 0.9156
Epoch 77/100
35/35 [==============================] - 0s 741us/step - loss: 0.2028 - accuracy: 0.9156
Epoch 78/100
35/35 [==============================] - 0s 667us/step - loss: 0.2010 - accuracy: 0.9192
Epoch 79/100
35/35 [==============================] - 0s 749us/step - loss: 0.1998 - accuracy: 0.9174
Epoch 80/100
35/35 [==============================] - 0s 668us/step - loss: 0.1988 - accuracy: 0.9183
Epoch 81/100
35/35 [==============================] - 0s 584us/step - loss: 0.1978 - accuracy: 0.9192
Epoch 82/100
35/35 [==============================] - 0s 693us/step - loss: 0.1971 - accuracy: 0.9174
Epoch 83/100
35/35 [==============================] - 0s 707us/step - loss: 0.1963 - accuracy: 0.9174
Epoch 84/100
35/35 [==============================] - 0s 724us/step - loss: 0.1953 - accuracy: 0.9183
Epoch 85/100
35/35 [==============================] - 0s 808us/step - loss: 0.1948 - accuracy: 0.9192
Epoch 86/100
 1/35 [..............................] - ETA: 0s - loss: 0.1055 - accuracy: 0.9375
Epoch 00086: saving model to checkpoints/weights.86.hdf5
35/35 [==============================] - 0s 953us/step - loss: 0.1935 - accuracy: 0.9192
Epoch 87/100
35/35 [==============================] - 0s 632us/step - loss: 0.1915 - accuracy: 0.9192
Epoch 88/100
35/35 [==============================] - 0s 634us/step - loss: 0.1910 - accuracy: 0.9211
Epoch 89/100
35/35 [==============================] - 0s 664us/step - loss: 0.1905 - accuracy: 0.9201
Epoch 90/100
35/35 [==============================] - 0s 685us/step - loss: 0.1895 - accuracy: 0.9192
Epoch 91/100
35/35 [==============================] - 0s 559us/step - loss: 0.1882 - accuracy: 0.9220
Epoch 92/100
35/35 [==============================] - 0s 526us/step - loss: 0.1863 - accuracy: 0.9220
Epoch 93/100
35/35 [==============================] - 0s 567us/step - loss: 0.1860 - accuracy: 0.9220
Epoch 94/100
35/35 [==============================] - 0s 666us/step - loss: 0.1848 - accuracy: 0.9238
Epoch 95/100
35/35 [==============================] - 0s 647us/step - loss: 0.1840 - accuracy: 0.9220
Epoch 96/100
35/35 [==============================] - 0s 651us/step - loss: 0.1829 - accuracy: 0.9238
Epoch 97/100
35/35 [==============================] - 0s 618us/step - loss: 0.1816 - accuracy: 0.9229
Epoch 98/100
35/35 [==============================] - 0s 785us/step - loss: 0.1807 - accuracy: 0.9247
Epoch 99/100
35/35 [==============================] - 0s 894us/step - loss: 0.1804 - accuracy: 0.9238
Epoch 100/100
35/35 [==============================] - 0s 763us/step - loss: 0.1797 - accuracy: 0.9256
12/12 - 0s - loss: 0.3984 - accuracy: 0.8750
Loss: 0.39835700392723083, Accuracy: 0.875

In [14]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn_new = tf.keras.models.Sequential()

# First hidden layer
nn_new.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_new.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_new.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model
nn_new.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Restore the model weights
nn_new.load_weights("checkpoints/weights.86.hdf5")

# Evaluate the model using the test data
model_loss, model_accuracy = nn_new.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.3787 - accuracy: 0.8750
Loss: 0.37873151898384094, Accuracy: 0.875

In [15]:
# Export our model to HDF5 file
nn_new.save("trained_attrition.h5")

In [16]:
# Import the model to a new object
nn_imported = tf.keras.models.load_model('trained_attrition.h5')
# Evaluate the model using the test data
model_loss, model_accuracy = nn_new.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.3787 - accuracy: 0.8750
Loss: 0.37873151898384094, Accuracy: 0.875